module.exports = {
    "suggestions": [{
            "value": "г Москва, ул Валовая",
            "unrestricted_value": "г Москва, ул Валовая",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": null,
                "house_kladr_id": null,
                "house_type": null,
                "house_type_full": null,
                "house": null,
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "fias_level": "7",
                "kladr_id": "77000000000092700",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 6",
            "unrestricted_value": "г Москва, ул Валовая, д 6",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "8d126ef4-1adc-4eca-8f7b-5c47715e3b09",
                "house_kladr_id": "7700000000009270002",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "6",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "8d126ef4-1adc-4eca-8f7b-5c47715e3b09",
                "fias_level": "8",
                "kladr_id": "7700000000009270002",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 8/18",
            "unrestricted_value": "г Москва, ул Валовая, д 8/18",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "b7322145-677d-4439-9ca9-713b7fc98b9e",
                "house_kladr_id": "7700000000009270005",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "8/18",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "b7322145-677d-4439-9ca9-713b7fc98b9e",
                "fias_level": "8",
                "kladr_id": "7700000000009270005",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 10",
            "unrestricted_value": "г Москва, ул Валовая, д 10",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "ed7927a8-6d99-440a-9621-29b384b735ed",
                "house_kladr_id": "7700000000009270007",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "10",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "ed7927a8-6d99-440a-9621-29b384b735ed",
                "fias_level": "8",
                "kladr_id": "7700000000009270007",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 11/19",
            "unrestricted_value": "г Москва, ул Валовая, д 11/19",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "98839d9e-38f2-4b7a-a8ca-ad9d42e02d56",
                "house_kladr_id": "7700000000009270008",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "11/19",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "98839d9e-38f2-4b7a-a8ca-ad9d42e02d56",
                "fias_level": "8",
                "kladr_id": "7700000000009270008",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 20",
            "unrestricted_value": "г Москва, ул Валовая, д 20",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "a260d4c2-dfea-4d05-9e86-96494c180219",
                "house_kladr_id": "7700000000009270012",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "20",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "a260d4c2-dfea-4d05-9e86-96494c180219",
                "fias_level": "8",
                "kladr_id": "7700000000009270012",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 26",
            "unrestricted_value": "г Москва, ул Валовая, д 26",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "80c2e2c8-5886-44dd-87a4-7904b50dcba5",
                "house_kladr_id": "7700000000009270029",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "26",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "80c2e2c8-5886-44dd-87a4-7904b50dcba5",
                "fias_level": "8",
                "kladr_id": "7700000000009270029",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 29",
            "unrestricted_value": "г Москва, ул Валовая, д 29",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "74881bb7-427f-419e-a258-492f1edc85fc",
                "house_kladr_id": "7700000000009270015",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "29",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "74881bb7-427f-419e-a258-492f1edc85fc",
                "fias_level": "8",
                "kladr_id": "7700000000009270015",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 30",
            "unrestricted_value": "г Москва, ул Валовая, д 30",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "a0ea4a32-ad4f-4a69-a2c8-aac88a5c4032",
                "house_kladr_id": "7700000000009270018",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "30",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "a0ea4a32-ad4f-4a69-a2c8-aac88a5c4032",
                "fias_level": "8",
                "kladr_id": "7700000000009270018",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        },
        {
            "value": "г Москва, ул Валовая, д 31",
            "unrestricted_value": "г Москва, ул Валовая, д 31",
            "data": {
                "postal_code": "115054",
                "country": "Россия",
                "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "region_kladr_id": "7700000000000",
                "region_with_type": "г Москва",
                "region_type": "г",
                "region_type_full": "город",
                "region": "Москва",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                "city_kladr_id": "7700000000000",
                "city_with_type": "г Москва",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Москва",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": "a5fe2694-c8b3-45fe-ba1d-f2de0fad53c8",
                "street_kladr_id": "77000000000092700",
                "street_with_type": "ул Валовая",
                "street_type": "ул",
                "street_type_full": "улица",
                "street": "Валовая",
                "house_fias_id": "3ee68906-f6ec-4b66-b60d-1c2bf9a6bae3",
                "house_kladr_id": "7700000000009270020",
                "house_type": "д",
                "house_type_full": "дом",
                "house": "31",
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "postal_box": null,
                "fias_id": "3ee68906-f6ec-4b66-b60d-1c2bf9a6bae3",
                "fias_level": "8",
                "kladr_id": "7700000000009270020",
                "capital_marker": "0",
                "okato": "45286560000",
                "oktmo": "45376000",
                "tax_office": "7705",
                "tax_office_legal": null,
                "timezone": null,
                "geo_lat": null,
                "geo_lon": null,
                "beltway_hit": null,
                "beltway_distance": null,
                "qc_geo": null,
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": null,
                "qc": null
            }
        }
    ]
};